"""add_schema_foundation_sources_translations_usage

Revision ID: 364f650a2b1f
Revises: 5ddf78bdb32d
Create Date: 2026-06-20 10:31:50.310160

Schema foundation for the library architecture (task #2):
  - New tables: sources (availability), translations (multilingual), knowledge_notes,
    usage_categories, processing_steps.
  - MusicPiece new columns: slug (UNIQUE), difficulty_grade, difficulty_notes,
    lyrics_translation_pl (legacy fallback).
  - MusicFile new columns: kind (semantic enum), opens_externally, version.

render_as_batch=True in env.py handles SQLite ALTER TABLE limitations.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364f650a2b1f'
down_revision: Union[str, Sequence[str], None] = '5ddf78bdb32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('knowledge_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_piece_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('HISTORICAL', 'STYLISTIC', 'HARMONIC', 'PERFORMANCE', 'GENERAL', name='knowledgecategory'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['music_piece_id'], ['music_pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('piece_usage_categories',
    sa.Column('music_piece_id', sa.Integer(), nullable=False),
    sa.Column('usage_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['music_piece_id'], ['music_pieces.id'], ),
    sa.ForeignKeyConstraint(['usage_category_id'], ['usage_categories.id'], ),
    sa.PrimaryKeyConstraint('music_piece_id', 'usage_category_id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_piece_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('EXTERNAL_LINK', 'EVENT_ENSEMBLE', 'LOCAL_UPLOAD', name='sourcetype'), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('rights_status', sa.Enum('PUBLIC_DOMAIN', 'LICENSED', 'UNKNOWN', name='rightsstatus'), nullable=True),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('ensemble', sa.String(length=255), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['music_piece_id'], ['music_pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_piece_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.Enum('LITERAL', 'SINGABLE', 'RHYMED', name='translationkind'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['music_piece_id'], ['music_pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_piece_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('output_file_id', sa.Integer(), nullable=True),
    sa.Column('step_key', sa.String(length=50), nullable=False),
    sa.Column('step_label', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['music_piece_id'], ['music_pieces.id'], ),
    sa.ForeignKeyConstraint(['output_file_id'], ['music_files.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['music_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('music_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kind', sa.Enum('SOURCE_SCAN', 'SOURCE_PDF', 'OMR_RAW', 'CORRECTED', 'FINAL', 'REFERENCE', 'EDITABLE', 'OTHER', name='musicfilekind'), nullable=True))
        batch_op.add_column(
            sa.Column(
                'opens_externally',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('0'),
            )
        )

    with op.batch_alter_table('music_pieces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lyrics_translation_pl', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('difficulty_grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('difficulty_notes', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_music_pieces_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('music_pieces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_music_pieces_slug'))
        batch_op.drop_column('difficulty_notes')
        batch_op.drop_column('difficulty_grade')
        batch_op.drop_column('slug')
        batch_op.drop_column('lyrics_translation_pl')

    with op.batch_alter_table('music_files', schema=None) as batch_op:
        batch_op.drop_column('opens_externally')
        batch_op.drop_column('kind')
        batch_op.drop_column('version')

    op.drop_table('processing_steps')
    op.drop_table('translations')
    op.drop_table('sources')
    op.drop_table('piece_usage_categories')
    op.drop_table('knowledge_notes')
    op.drop_table('usage_categories')
    # ### end Alembic commands ###
