"""add_extracted_text_to_music_file

Revision ID: 5ddf78bdb32d
Revises: 8cc60e7f79d3
Create Date: 2026-06-07 08:34:40.956517

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ddf78bdb32d"
down_revision: Union[str, Sequence[str], None] = "8cc60e7f79d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("music_files", schema=None) as batch_op:
        batch_op.add_column(sa.Column("extracted_text", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ocr_confidence", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("music_files", schema=None) as batch_op:
        batch_op.drop_column("ocr_confidence")
        batch_op.drop_column("extracted_text")

    # ### end Alembic commands ###
