"""initial_schema

Revision ID: 8cc60e7f79d3
Revises:
Create Date: 2026-06-07 08:34:22.722674

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cc60e7f79d3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "music_pieces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("composer", sa.String(length=255), nullable=True),
        sa.Column("arranger", sa.String(length=255), nullable=True),
        sa.Column("lyrics_author", sa.String(length=255), nullable=True),
        sa.Column("music_author", sa.String(length=255), nullable=True),
        sa.Column("harmony_author", sa.String(length=255), nullable=True),
        sa.Column("genre", sa.String(length=100), nullable=True),
        sa.Column("key_signature", sa.String(length=50), nullable=True),
        sa.Column("time_signature", sa.String(length=50), nullable=True),
        sa.Column("measures_count", sa.Integer(), nullable=True),
        sa.Column("tempo", sa.String(length=100), nullable=True),
        sa.Column("occasion", sa.String(length=100), nullable=True),
        sa.Column("liturgical_season", sa.String(length=100), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("lyrics", sa.Text(), nullable=True),
        sa.Column("musescore_link", sa.String(length=512), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "music_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("music_piece_id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column(
            "file_type",
            sa.Enum("SCAN", "PDF", "MUSESCORE", "XML", "TEXT", "OTHER", name="filetype"),
            nullable=False,
        ),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_processed", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["music_piece_id"],
            ["music_pieces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "music_piece_tags",
        sa.Column("music_piece_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["music_piece_id"],
            ["music_pieces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("music_piece_id", "tag_id"),
    )
    op.create_table(
        "usage_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("music_piece_id", sa.Integer(), nullable=False),
        sa.Column("usage_date", sa.DateTime(), nullable=False),
        sa.Column("event_name", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["music_piece_id"],
            ["music_pieces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usage_history")
    op.drop_table("music_piece_tags")
    op.drop_table("music_files")
    op.drop_table("tags")
    op.drop_table("music_pieces")
    # ### end Alembic commands ###
